name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install # Ensure dependencies are installed

      - name: Run tests
        run: npm test # Replace with actual test command

  build:
    needs: test # This ensures 'build' runs only if 'test' succeeds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .
          docker tag myapp:latest ${{ vars.DOCKER_USERNAME }}/myapp:${{ github.sha }}

      - name: Push Docker image
        run: docker push ${{ vars.DOCKER_USERNAME }}/myapp:${{ github.sha }}
