name: Build and Push Docker Image

on:
  push:
    branches:
      - master# or any branch you want this to run on

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Use appropriate Node.js version for your project

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test # Modify with the test command for your project

      - name: Test success
        if: success()
        run: echo "Tests passed, proceeding to Docker build"

      - name: Test failed
        if: failure()
        run: echo "Tests failed, stopping the build"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }} # Set in GitHub secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # Set in GitHub secrets

      - name: Build Docker image
        if: success()
        run: |
          docker build -t 1myapp:latest .
          docker tag 1myapp:latest ${{ vars.DOCKER_USERNAME }}/1myapp:${{ github.sha }}

      - name: Push Docker image
        if: success()
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/1myapp:${{ github.sha }}
